[GLOBAL]
pants_version = "2.16.0"

backend_packages.add = [
  "pants.backend.python",
]

[source]
root_patterns = ["python", "airflow"]


[python]
pip_version = "22.3"

interpreter_constraints = ["==3.10.*"]
enable_resolves = true

